### PR TITLE
Fix wrong socket location

### LINKED ISSUE #21: Broken on hyprland-git
When attempting to use hyprsome on hyprland-git, i get this error
```
thread 'main' panicked at /home/beyley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyprland-0.3.1/src/data/regular.rs:25:19:
A error occured while parsing the output from the hypr socket: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by MaximumWoahverdrive**
Fixes #21 
Updated dependencies and added socket path logic from upstream (where they are pub(crate) and therefore unavailable to us downstream)
the hyprland-rs dependency should be updated to 0.4 or higher once available

Please excuse my terrible rust, this is my first time using it :)

### CODE REVIEW

**Comment by sopa0** [comment]
Hi, thanks for the MR
I'm currently celebrating Pascha and I don't have my pc on me, I should be able to take a look on Sunday evening (GMT)

**Comment by Beyley** [comment]
can confirm this PR fixes #21 for me!

**Comment by GlassedIdiot** [comment]
This current version that @MaximumWoahverdrive has compiled and provided the tar for seems to work perfectly fine with the latest hyprland update. I would like to express my thanks to @MaximumWoahverdrive .Since this has proved really helpful.

**Comment by rearden888** [comment]
+1 confirmed the @MaximumWoahverdrive version works for me as well, hyrpland 0.40 on Arch.  Thanks for your work!  Hope it can get merged soon.

**Comment by sopa0** [comment]
Merged, thanks for the PR

**Pull request merged**
